<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="4" passed="2" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2017-11-19T17:02:15Z" name="LoginTestSuite" finished-at="2017-11-19T17:02:19Z" duration-ms="4585">
    <groups>
    </groups>
    <test started-at="2017-11-19T17:02:15Z" name="Test Cases" finished-at="2017-11-19T17:02:19Z" duration-ms="4585">
      <class name="testlogin.mavendependency.AppTest">
        <test-method is-config="true" signature="invokeBrowser()[pri:0, instance:testlogin.mavendependency.AppTest@2925bf5b]" started-at="2017-11-19T18:02:15Z" name="invokeBrowser" finished-at="2017-11-19T18:02:19Z" duration-ms="4012" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invokeBrowser -->
        <test-method signature="displayAllUsers()[pri:0, instance:testlogin.mavendependency.AppTest@2925bf5b]" started-at="2017-11-19T18:02:19Z" name="displayAllUsers" description="This test case displays all the users list available" finished-at="2017-11-19T18:02:19Z" duration-ms="284" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- displayAllUsers -->
        <test-method signature="userValidations(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testlogin.mavendependency.AppTest@2925bf5b]" started-at="2017-11-19T18:02:19Z" name="userValidations" description="This test case check for the validations" data-provider="UserDetails" finished-at="2017-11-19T18:02:19Z" duration-ms="3" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[raja12]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[rj2@gmail.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[12334]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[12334]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertFalse(Assert.java:63)
	at org.testng.Assert.assertFalse(Assert.java:73)
	at testlogin.mavendependency.AppTest.userValidations(AppTest.java:66)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- userValidations -->
        <test-method signature="newUser()[pri:0, instance:testlogin.mavendependency.AppTest@2925bf5b]" started-at="2017-11-19T18:02:19Z" name="newUser" description="This test case navigates back to the new user creation page" finished-at="2017-11-19T18:02:19Z" depends-on-methods="testlogin.mavendependency.AppTest.displayAllUsers" duration-ms="162" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- newUser -->
        <test-method signature="createUser(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testlogin.mavendependency.AppTest@2925bf5b]" started-at="2017-11-19T18:02:19Z" name="createUser" description="This test case takes the credentials and try to create a new user if the name and email are unique" data-provider="UserDetails" finished-at="2017-11-19T18:02:19Z" depends-on-methods="testlogin.mavendependency.AppTest.userValidations" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createUser -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:testlogin.mavendependency.AppTest@2925bf5b]" started-at="2017-11-19T18:02:19Z" name="closeBrowser" finished-at="2017-11-19T18:02:19Z" duration-ms="109" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- testlogin.mavendependency.AppTest -->
    </test> <!-- Test Cases -->
  </suite> <!-- LoginTestSuite -->
</testng-results>
